name: bundelizer
description: Flutter plugin to store/retrieve compressed data in a structured way.
version: 0.1.0
repository: https://github.com/rusoleal/bundelizer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.25.8

topics:
  - persistence
  - storage